# you can delete this line if you're not using Docker
image: python:latest

#include:
#  - template: Security/SAST.gitlab-ci.yml

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V  # Print out python version for debugging
  - python3 -m venv venv
  - source venv/bin/activate

sphinx-html-docs:
  stage: build
  script:
    - pip install numpy sphinx sphinx-rtd-theme tox
    - tox
  artifacts:
    paths:
      - .tox/doc/build/doc
    expire_in: 1 day

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -rv .tox/doc/build/doc/* public/
  artifacts:
    paths:
      - public
